import { Client } from '@notionhq/client';
import type { Todo } from './storage.js';

export type ReportRange = { from: string; to: string };

function inRange(iso: string | undefined, from: Date, to: Date): boolean {
  if (!iso) return false;
  const t = new Date(iso).getTime();
  return t >= from.getTime() && t <= to.getTime();
}

function todoBlocks(todos: Todo[], checked: boolean) {
  return todos.map((t) => ({
    object: 'block' as const,
    type: 'to_do' as const,
    to_do: {
      rich_text: [{ type: 'text' as const, text: { content: t.text } }],
      checked,
      color: 'default' as const,
    },
  }));
}

function heading(text: string) {
  return {
    object: 'block' as const,
    type: 'heading_2' as const,
    heading_2: {
      rich_text: [{ type: 'text' as const, text: { content: text } }],
    },
  };
}

function paragraph(text: string) {
  return {
    object: 'block' as const,
    type: 'paragraph' as const,
    paragraph: {
      rich_text: [{ type: 'text' as const, text: { content: text } }],
    },
  };
}

function formatDate(d: Date) {
  return d.toISOString().slice(0, 10);
}

export async function sendNotionReport(opts: {
  token: string;
  pageId: string;
  todos: Todo[];
  range: ReportRange;
}): Promise<{ url: string }> {
  const { token, pageId, todos, range } = opts;

  const fromDate = new Date(`${range.from}T00:00:00`);
  const toDate = new Date(`${range.to}T23:59:59.999`);

  const completed = todos.filter((t) => t.done && inRange(t.completedAt, fromDate, toDate));
  const open = todos.filter((t) => !t.done && inRange(t.createdAt, fromDate, toDate));

  const sameDay = range.from === range.to;
  const title = sameDay
    ? `Todo Report — ${range.from}`
    : `Todo Report — ${range.from} → ${range.to}`;

  const children: any[] = [];
  children.push(heading(`Completed (${completed.length})`));
  if (completed.length === 0) children.push(paragraph('No completed tasks in this range.'));
  else children.push(...todoBlocks(completed, true));

  children.push(heading(`Open (${open.length})`));
  if (open.length === 0) children.push(paragraph('No open tasks in this range.'));
  else children.push(...todoBlocks(open, false));

  children.push({ object: 'block', type: 'divider', divider: {} });
  children.push(paragraph(`Generated by simple-todo at ${formatDate(new Date())}`));

  const notion = new Client({ auth: token });
  const page = await notion.pages.create({
    parent: { page_id: pageId },
    properties: {
      title: { title: [{ type: 'text', text: { content: title } }] },
    },
    children,
  });

  const url = (page as { url?: string }).url ?? '';
  return { url };
}
